module SDLPixel

let SDL_PIXELTYPE_UNKNOWN=0
let SDL_PIXELTYPE_INDEX1=1
let SDL_PIXELTYPE_INDEX4=2
let SDL_PIXELTYPE_INDEX8=3
let SDL_PIXELTYPE_PACKED8=4
let SDL_PIXELTYPE_PACKED16=5
let SDL_PIXELTYPE_PACKED32=6
let SDL_PIXELTYPE_ARRAYU8=7
let SDL_PIXELTYPE_ARRAYU16=8
let SDL_PIXELTYPE_ARRAYU32=9
let SDL_PIXELTYPE_ARRAYF16=10
let SDL_PIXELTYPE_ARRAYF32=11

let SDL_PACKEDORDER_NONE=0
let SDL_PACKEDORDER_XRGB=1
let SDL_PACKEDORDER_RGBX=2
let SDL_PACKEDORDER_ARGB=3
let SDL_PACKEDORDER_RGBA=4
let SDL_PACKEDORDER_XBGR=5
let SDL_PACKEDORDER_BGRX=6
let SDL_PACKEDORDER_ABGR=7
let SDL_PACKEDORDER_BGRA=8

let SDL_PACKEDLAYOUT_NONE=0
let SDL_PACKEDLAYOUT_332=1
let SDL_PACKEDLAYOUT_4444=2
let SDL_PACKEDLAYOUT_1555=3
let SDL_PACKEDLAYOUT_5551=4
let SDL_PACKEDLAYOUT_565=5
let SDL_PACKEDLAYOUT_8888=6
let SDL_PACKEDLAYOUT_2101010=7
let SDL_PACKEDLAYOUT_1010102=9

let SDL_DEFINE_PIXELFORMAT (typ, order, layout, bits, bytes) =
    ((1 <<< 28) ||| ((typ) <<< 24) ||| ((order) <<< 20) ||| ((layout) <<< 16) ||| ((bits) <<< 8) ||| ((bytes) <<< 0)) |> uint32

let SDL_PIXELFORMAT_ARGB8888 =
    SDL_DEFINE_PIXELFORMAT(SDL_PIXELTYPE_PACKED32, SDL_PACKEDORDER_ARGB, SDL_PACKEDLAYOUT_8888, 32, 4)




